import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter, withViewTransitions } from '@angular/router';
import { provideClientHydration } from '@angular/platform-browser';
import { routes } from './app.routes';
import {
  LucideAngularModule,
  Files,
  Sun,
  Copy,
  Check,
  Moon,
  Instagram,
  Github,
  Trash,
  Bell,
  Rss,
  Megaphone,
  Ban,
  CircleCheck,
  Info,
  X,
  Bug,
  ChevronLeft,
  ChevronRight,
  ArrowUpRight,
  Shield,
  EllipsisVertical,
  Menu,
  CircleUser,
  TriangleAlert,
  MousePointerClick,
  MessageSquareDot,
  LoaderCircle,
  LayoutTemplate,
  TextCursorInput,
  Captions,
  WholeWord,
  ArrowRight,
  Command,
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes, withViewTransitions()),
    provideClientHydration(),
    importProvidersFrom(
      LucideAngularModule.pick({
        Files,
        Sun,
        Copy,
        Check,
        Moon,
        Instagram,
        Github,
        Trash,
        Bell,
        Rss,
        Megaphone,
        Ban,
        TriangleAlert,
        CircleCheck,
        Info,
        X,
        Bug,
        ChevronLeft,
        ChevronRight,
        ArrowUpRight,
        Shield,
        EllipsisVertical,
        Menu,
        CircleUser,
        MousePointerClick,
        MessageSquareDot,
        LoaderCircle,
        LayoutTemplate,
        TextCursorInput,
        Captions,
        WholeWord,
        ArrowRight,
        Command,
      })
    ),
  ],
};
